export const USER_SIGN_IN_ACTION = "USER_SIGN_IN_ACTION";

export const USER_SIGN_UP_ACTION = "USER_SIGN_UP_ACTION";

export const UPDATE_USER = "UPDATE_USER";

export const GET_USER_DETAIL = "GET_USER_DETAIL";

export const UPLOAD_USER_IMAGE = "UPLOAD_USER_IMAGE";
